version: "3"

services:
  api:
    image: nilswitt/vacxpass-server:latest
    ports:
    - 3000:3000
    volumes:
    - ./keys:/usr/src/app/keys
    environment:
      CERT_PASS: pass
      PassTypeIdentifier: pass.de.example
      TeamIdentifier: XXXXXXXXXX